hive/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.http import Http404

from hive.admin import admin_site
import programs.urls
import volunteers.urls
import dashboard.urls
import courses.urls


def not_found(request):
    raise Http404


if settings.SITE == 'programs':
    urlpatterns = [
        url(r'^', include('django.contrib.auth.urls')),
        url(r'^', include(programs.urls)),
    ]

elif settings.SITE == 'courses':
    urlpatterns = [
        url(r'^', include(courses.urls)),
        url(r'^', include('social_django.urls', namespace='social'))
    ]

else:
    urlpatterns = [
        url(r'^admin/', include(admin_site.urls)),
        url(r'^volunteer/', include(volunteers.urls)),
        url(r'^', include(dashboard.urls)),
        url(r'^', include('django.contrib.auth.urls')),
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

volunteers/urls.py
from django.conf.urls import url
from volunteers import views


urlpatterns = [
    url('^$', views.opportunities, name='volunteers-opportunities'),
    url('^profile/$', views.profile, name='volunteers-profile'),
    url('^(?P<slug>[^/]+)/complete/(?P<signup_id>[^/]+)/$',
        views.signup_complete, name='volunteers-signup-complete'),
    url('^(?P<slug>[^/]+)/$', views.signup, name='volunteers-signup'),
]

volunteers/models.py
from dateutil.relativedelta import relativedelta
from django.utils import timezone
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.contrib.postgres.fields import JSONField
from django.template.defaultfilters import slugify
from django.utils.dateformat import format as format_date

from contacts.models import Contact, DemographicsModel
from questionnaires.models import Questionnaire
from programs.query import SemesterQuerySet
from . import constants
from .query import VolunteerRequirementQuerySet


class Volunteer(DemographicsModel, Contact):
    shirt_size = models.CharField(max_length=5, choices=constants.SHIRT_SIZE_CHOICES, blank=True)
    full_legal_name = models.CharField(max_length=128, blank=True)
    emergency_contact = models.TextField(
        blank=True, help_text=(
            'Provide the name and phone number of the person we should '
            'contact in the event of an emergency'))
    is_student = models.BooleanField()
    school = models.CharField(blank=True, max_length=255)
    last_agreement_date = models.DateTimeField(null=True, blank=True)
    extra_data = JSONField(null=True, blank=True)
    languages = JSONField(null=True, blank=True)

    programs = models.ManyToManyField('programs.Program', through='VolunteerAssignment')

    objects = SemesterQuerySet.as_manager('programs__start_date')

    class Meta:
        ordering = ['first_name', 'last_name']

    @property
    def agreement_expired(self):
        if not self.last_accepted_agreement:
            return True
        agreement_age = timezone.now() - self.last_accepted_agreement
        return agreement_age >= settings.VOLUNTEER_TERMS_RENEWAL_PERIOD

    def get_upcoming_training_sessions(self):
        sessions = TrainingSession.objects.filter(
            date__gte=timezone.now()).order_by('date', 'start_time')

        if self.user.is_superuser:
            return sessions

        my_opportunities = (VolunteerOpportunity.objects
                            .exclude(status='ARCHIVED')
                            .filter(signups__volunteer=self))
        my_programs = self.programs.all()

        return sessions.filter(
            Q(programs__in=my_programs) |
            Q(programs=None, opportunities__in=my_opportunities) |
            Q(facilitators=self)
        ).distinct()


class VolunteerRequirementType(models.Model):
    name = models.CharField(max_length=64)
    slug = models.SlugField()
    responsible_party = models.CharField(max_length=16, choices=(
        ('VOLUNTEER', 'Volunteer'),
        ('STAFF', 'Staff')
    ), default='VOLUNTEER')
    renewal_months = models.IntegerField(null=True, blank=True)
    instructions = models.TextField(help_text="markdown supported", blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Volunteer requirement'
        verbose_name_plural = 'Volunteer requirements'


class VolunteerRequirement(models.Model):
    requirement_type = models.ForeignKey(
        VolunteerRequirementType, related_name='pending_or_completed_requirements',
        on_delete=models.PROTECT)
    volunteer = models.ForeignKey(Volunteer, related_name='requirements')
    status = models.CharField(
        max_length=16, choices=constants.VOLUNTEER_REQUIREMENT_STATUS_CHOICES,
        default='INCOMPLETE')
    completed_date = models.DateField(null=True, blank=True)
    notes = models.TextField(blank=True)
    expire_date = models.DateField(null=True, blank=True)

    objects = VolunteerRequirementQuerySet.as_manager()

    def save(self, *args, **kwargs):
        if not self.expire_date and self.completed_date and self.requirement_type.renewal_months:
            delta = relativedelta(months=self.requirement_type.renewal_months)
            self.expire_date = self.completed_date + delta
        super().save(*args, **kwargs)

    def is_expired(self, as_of=None):
        as_of = as_of or timezone.now()
        return self.expire_date is None or self.expired_ate >= as_of

    @property
    def name(self):
        return self.requirement_type.name

    @property
    def instructions(self):
        return self.requirement_type.instructions

    def __str__(self):
        return self.name


class VolunteerOpportunity(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField()
    short_description = models.TextField()
    description_url = models.URLField(blank=True)
    role = models.CharField(max_length=32, choices=constants.VOLUNTEER_ROLE_CHOICES, blank=True)
    photo = models.ImageField(blank=True)
    status = models.CharField(max_length=16, choices=(
        ('DRAFT', 'Draft'),
        ('PUBLISHED', 'Published'),
        ('ARCHIVED', 'Archived')
    ), default='DRAFT')
    order = models.IntegerField(default=0)
    questionnaire = models.ForeignKey(Questionnaire, blank=True, null=True)
    confirmation_extra_info = models.TextField(blank=True)
    programs = models.ManyToManyField(
        'programs.Program', blank=True, related_name='volunteer_opportunities')
    requirements = models.ManyToManyField(VolunteerRequirementType, blank=True)
    role = models.CharField(max_length=32, choices=constants.VOLUNTEER_ROLE_CHOICES, blank=True)

    objects = SemesterQuerySet.as_manager('programs__start_date')

    def __str__(self):
        if self.status == 'ARCHIVED':
            return self.name + ' (archived)'
        if self.status == 'DRAFT':
            return self.name + ' (draft)'
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    @property
    def program_locations(self):
        locations = self.programs.values_list('location__name', flat=True)
        return locations.distinct()

    class Meta:
        verbose_name_plural = 'Volunteer opportunities'
        ordering = ['order']


class TrainingSession(models.Model):
    opportunities = models.ManyToManyField(
        VolunteerOpportunity, blank=True, related_name='training_sessions',
        help_text="This session will be for volunteers who have signed up for this opportunity")
    programs = models.ManyToManyField(
        'programs.Program', blank=True, related_name='training_sessions',
        help_text="This session will be for volunteers assigned to these programs.")
    location = models.ForeignKey('programs.Location')
    date = models.DateField()
    start_time = models.TimeField(null=True, blank=True)
    end_time = models.TimeField(null=True, blank=True)
    name = models.CharField(max_length=128)
    description = models.TextField(blank=True)
    facilitators = models.ManyToManyField(
        Volunteer, blank=True, related_name='facilitated_training_sessions')
    attendees = models.ManyToManyField(
        Volunteer, blank=True, related_name='attended_training_sessions')
    location_info = models.TextField(
        'Location info / parking instructions', blank=True)
    notes = models.TextField(blank=True)

    @property
    def date_description(self):
        datestr = format_date(self.date, 'N j, Y')
        if self.start_time:
            datestr += ', ' + format_date(self.start_time, 'P')
        if self.end_time:
            datestr += ' - ' + format_date(self.end_time, 'P')
        return datestr

    @property
    def invitees(self):
        programs = self.programs.all()
        opportunities = self.opportunities.all()
        if opportunities and not programs:
            # get volunteers who have signed up for the associated opportunity
            filter = Q(signups__opportunity__in=opportunities)
        elif programs:
            # get volunteers who have signed up for the associated programs
            filter = Q(programs__in=programs)

        # exclude volunteers who have already attended training for this opportunity
        filter &= ~Q(attended_training_sessions__opportunities__in=opportunities)

        # include facilitators
        filter |= Q(facilitated_training_sessions=self)

        # include attendees of THIS session
        filter |= Q(attended_training_sessions=self)

        return Volunteer.objects.filter(filter).distinct()

    def __str__(self):
        return self.name


class VolunteerSignup(models.Model):
    """
    Represents the event that a volunteer signed up for an opportunity.
    """
    date = models.DateTimeField(default=timezone.now, null=True)
    volunteer = models.ForeignKey(Volunteer, related_name='signups')
    opportunity = models.ForeignKey(VolunteerOpportunity, related_name='signups')
    form_data = JSONField(null=True, blank=True)

    objects = SemesterQuerySet.as_manager('opportunity__programs__start_date')

    def __str__(self):
        return '{} - {}'.format(self.opportunity, self.volunteer)

    @property
    def requirements(self):
        return VolunteerRequirement.objects.filter(assignments__in=self.assignments.all())

    @property
    def training_sessions(self):
        q = models.Q(programs=None, opportunities=self.opportunity)
        if self.assignments.count() > 0:
            programs = self.assignments.values_list('program', flat=True)
            q |= models.Q(programs__in=programs)
        return TrainingSession.objects.filter(q).distinct()

    @property
    def attended_training_sessions(self):
        return self.training_sessions.filter(attendees=self.volunteer).distinct()

    @property
    def session_attendances(self):
        from programs.models import VolunteerAttendance
        return VolunteerAttendance.objects.filter(
            volunteer=self.volunteer, session__program__in=self.opportunity.programs.all())


class VolunteerAssignment(models.Model):
    """
    Represents a volunteer's role for a given program. This is independent of the signup, although
    it can be created automatically during a signup, during which case the signup will be

volunteers/forms.py
from django import forms
from django.conf import settings

from hive.forms import BaseForm
from hive.utils import get_age
from hive.widgets import ProfilePhotoInput
from questionnaires.forms import QuestionnaireModelForm
from users import forms as user_forms
from volunteers import models, constants


class UserCreationForm(BaseForm, user_forms.UserCreationForm):
    pass


class UserChangeForm(BaseForm, user_forms.UserChangeForm):
    pass


class VolunteerForm(QuestionnaireModelForm):
    questionnaire_slug = 'volunteer-profile'

    def __init__(self, *args, **kwargs):
        self.language_fields = []
        instance = kwargs.get('instance', None)
        self.base_fields['email'].required = True
        self.base_fields['phone'].required = True
        self.base_fields['birth_date'].required = True

        # Add fields for language
        for lang_code, lang_name in settings.LANGUAGES:
            initial = None
            if instance and isinstance(instance.languages, dict):
                initial = instance.languages.get(lang_code)
            choices = ((None, ''),) + constants.LANGUAGE_PROFICENCY_CHOICES
            field = forms.ChoiceField(
                label=lang_name, required=True, choices=choices, initial=initial)
            self.base_fields['lang_{}'.format(lang_code)] = field

        super().__init__(*args, **kwargs)

        for lang_code, lang_name in settings.LANGUAGES:
            self.language_fields.append(self['lang_{}'.format(lang_code)])

    def save(self, commit=True):
        instance = super().save(commit=False)
        languages = {}
        for lang_code, lang_name in settings.LANGUAGES:
            key = 'lang_{}'.format(lang_code)
            languages[lang_code] = self.cleaned_data[key]
        instance.languages = languages
        instance.save()
        return instance

    def clean_birth_date(self):
        birth_date = self.cleaned_data['birth_date']
        if get_age(birth_date) < 13:
            raise forms.ValidationError(
                'You must be over 13 to volunteer with Bold Idea.')
        return birth_date

    class Meta:
        model = models.Volunteer
        fields = [
            'photo', 'first_name', 'last_name', 'address1', 'address2', 'city',
            'state', 'postal_code', 'email', 'phone', 'alt_phone',
            'is_student', 'company', 'school', 'birth_date',
            'emergency_contact', 'shirt_size', 'race', 'ethnicity', 'gender'
        ]
        widgets = {
            'photo': ProfilePhotoInput(
                message_default=(
                    "Click to change your profile photo. Make sure it clearly "
                    "shows your face! We use this to feature mentors on our "
                    "website.")
            ),
            'birth_date': forms.DateInput(attrs={
                # data-placeholder will only show placeholder when focused
                # (see hive/static/hive/js/init.js)
                'data-placeholder': 'MM/DD/YYYY'
            })
        }


class VolunteerSignupForm(QuestionnaireModelForm):
    questionnaire_data_field = 'form_data'
    birth_date = forms.DateField(required=True)
    full_legal_name = forms.CharField(required=True)
    agreement = forms.BooleanField(required=True)

    def __init__(self, *args, **kwargs):
        opportunity = kwargs.pop('opportunity', None)
        if opportunity and opportunity.questionnaire:
            self.questionnaire_slug = opportunity.questionnaire.slug
        super().__init__(*args, **kwargs)

    def clean_birth_date(self):
        birth_date = self.cleaned_data['birth_date']
        if get_age(birth_date) < 13:
            raise forms.ValidationError(
                'You must be over 13 to volunteer with Bold Idea.')
        return birth_date

    class Meta:
        model = models.VolunteerSignup
        exclude = ['volunteer', 'opportunity', 'form_data', 'date']

volunteers/templates/volunteers/base.html
{% extends "dashboard/base.html" %}

volunteers/templates/volunteers/opportunities.html
{% extends "volunteers/base.html" %}
{% load static thumbnail %}

{% block page_content %}
<h3>Volunteer Opportunities</h3>
<div class="row">
  {% for opportunity in opportunities %}
  <div class="col s12 m6 l4">
    <div class="card">
      <a class="card-image" href="{% url "volunteers-signup" slug=opportunity.slug %}">
        <img class="activator" src="{% thumbnail opportunity.photo 400x225 crop upscale %}">
        <span class="card-title">{{ opportunity.name }}</span>
      </a>
      <div class="card-content">
        {% with opportunity.program_locations.count as locations %}
        {% if locations > 0 %}
        <p class="locations">{{ locations }} location{{ locations|pluralize }}</p>
        {% endif %}
        {% endwith %}
        <p class="description">{{ opportunity.short_description }}</p>
      </div>
      <div class="card-action">
        <a href="{% url "volunteers-signup" slug=opportunity.slug %}">
          <i class="material-icons left">assignment_ind</i>
          Sign up
        </a>
      </div>
    </div>
  </div>
  {% if forloop.counter|divisibleby:3 %}
</div>
<div class="row">
  {% endif %}
  {% endfor %}
</div>
{% endblock %}

{% block extrajs %}{{ block.super }}
<script>
$(document).ready(function() {
  $('.modal').modal();
});
</script>
{% endblock %}

volunteers/templates/volunteers/profile.html
{% extends "volunteers/base.html" %}
{% load static questionnaire_tags material_tags material_form material_form_internal %}

{% block extracss %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static "questionnaires/css/style.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "dropify/css/dropify.min.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "hive/css/dropify-profile-photo.css" %}">
<style>
  .photo-instructions {
    font-size: 75%;
    font-style: italic;
    text-align: center;
  }
</style>
{% endblock %}

{% block page_content %}
{% include "hive/includes/pickers.html" %}
<div class="section">
  <h3>Volunteer Profile</h3>
  {% if not profile %}
  <p>
    Before you can sign up for a volunteer opportunity, you'll need to complete your Bold Idea profile. You'll
    only have to do this once. Next time you volunteer, just log in and go directly to the sign-up form.
  </p>
  {% endif %}
  <form enctype="multipart/form-data" method="POST" action=".">{% csrf_token %}
    {% form %}
    {% part form %}

    {% for field in form.hidden_fields %}
    {{ field }}
    {% endfor %}

    {% minimal_error_list form user_form %}

    <div class="card-panel">
      <div class="row">
        <div class="photo-upload col s12 m4">
          {{ form.photo }}
        </div>
        <div class="col s12 m4">
          {% field form.first_name %}
        </div>
        <div class="col s12 m4">
          {% field form.last_name %}
        </div>
        <div class="col s12 m8">
          {% field form.email %}
        </div>
        {% if not user %}
        {% with user_form as form %}
        <div class="col s12 m4">
          {% field form.password1 %}
        </div>
        <div class="col s12 m4">
          {% field form.password2 %}
        </div>
        {% endwith %}
        {% else %}
        <div class="col s12 m8">
          <i class="material-icons tiny">lock</i>
          <a href="#">Click here to change your password.</a>
        </div>
        {% endif %}
      </div>
      <div class="row">
        <div class="col s12 m6">
          {% field form.birth_date %}
        </div>
        <div class="col s12 m6">
          {% field form.shirt_size %}
        </div>
      </div>
      <div class="row">
        <div class="col s12 m6">
          <p>
            <label>Are you a student?</label>
          </p>
          <div class="switch">
            <label>
              No
              <input class="validate validate" id="id_is_student" name="is_student" type="checkbox">
              <span class="lever"></span>
              Yes
            </label>
          </div>
        </div>
        <div class="col s12 m6 company-field">
          {% field form.company %}
        </div>
        <div class="col s12 m6 school-field">
          {% field form.school %}
        </div>
      </div>
    </div>
    <div class="card-panel">
      <h5>Contact info</h5>
      <div class="row">
        <div class="col s12 m6">
          {% field form.address1 %}
        </div>
        <div class="col s12 m6">
          {% field form.address2 %}
        </div>
      </div>
      <div class="row">
        <div class="col s12 m4">
          {% field form.city %}
        </div>
        <div class="col s12 m4">
          {% field form.state %}
        </div>
        <div class="col s12 m4">
          {% field form.postal_code %}
        </div>
      </div>
      <div class="row">
        <div class="col s12 m6">
          {% field form.phone %}
        </div>
        <div class="col s12 m6">
          {% field form.alt_phone %}
        </div>
      </div>
      <div class="row">
        <div class="col s12">
          {% field form.emergency_contact %}
        </div>
      </div>
    </div>
    <div class="card-panel demographics">
      <h5>Gender, race, &amp; ethnicity</h5>
      <p class="disclaimer">
        The following information helps to ensure that we're providing diverse role models for our students,
        improve our outreach efforts and expand our programs into communities that need it the most. Bold Idea does
        not discriminate based on race, ethnicity, or gender.
      </p>
      <div class="row">
        <div class="col s12 m4">
          {% field form.gender %}
        </div>
        <div class="col s12 m4">
          {% field form.race %}
        </div>
        <div class="col s12 m4">
          {% field form.ethnicity %}
        </div>
      </div>
    </div>
    <div class="card-panel languages">
      <h5>Languages</h5>
      <p>Please rate your proficency in the following languages:</p>
      <div class="row">
        {% for lang_field in form.language_fields %}
        <div class="col s12 m4">
          {% field lang_field %}
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="card-panel questionnaire">
      <h5>Tell us about yourself!</h5>
      {% for question, field in form.questionnaire_fields %}
      <div class="row">
        <div class="col s12">
          {% question_field question field %}
        </div>
      </div>
      {% endfor %}
    </div>
    <div class="row submit-row">
      <div class="col s12 align-right">
        {% if next %}
        <p class="align-right">
          Press "Continue" to save your profile and continue to the next step.
        </p>
        <input type="submit" value="Continue" class="btn">
        {% else %}
        <input type="submit" value="Save" class="btn">
        {% endif %}
      </div>
    </div>
    {% endpart %}
    {% endform %}
    <input type="hidden" name="next" value="{{ next|default:"" }}">
  </form>
</div>

{% endblock %}

{% block extrajs %}
{{ block.super }}
<script src="{% static "dropify/js/dropify.min.js" %}"></script>
<script src="{% static "hive/js/dropify-profile-photo.js" %}"></script>
<script src="{% static "hive/js/material-pickers.js" %}"></script>
<script>
  (function($){
    $(document).ready(function() {
      $('#id_is_student').on('change', function() {
        $('.school-field').toggle(this.checked);
        $('.company-field').toggle(!this.checked);
      }).change();
    });
  })(jQuery);
</script>
{% endblock %}

volunteers/templates/volunteers/signup_complete.html
{% extends "volunteers/base.html" %}
{% block page_content %}
<h3>You rock, {{ signup.volunteer.first_name }}!</h3>

{% include "volunteers/includes/signup_complete.html" %}
{% endblock %}

volunteers/templates/volunteers/signup_complete_email.html
<p>Hey, {{ signup.volunteer.first_name }} -</p>

<p><strong>You rock!</strong></p>

{% include "volunteers/includes/signup_complete.html" %}