dashboard/urls.py
from django.conf.urls import url
from dashboard import views


urlpatterns = [
    url('^$', views.home, name='dashboard-home'),
    url('^programs/(?P<program_id>[^/]+)/$',
        views.program_site, name='dashboard-program-site'),
    url('^programs/(?P<program_id>[^/]+)/sessions/(?P<session_id>[^/]+)/$',
        views.program_site, name='dashboard-program-site'),
    url('^programs/(?P<program_id>[^/]+)/sessions/(?P<session_id>[^/]+)/$',
        views.program_site, name='dashboard-program-site'),
    url('^programs/exit-tickets/(?P<exit_ticket_id>[^/]+)/$',
        views.exit_ticket_answers, name='dashboard-exit-ticket-answers'),
    url('^programs/(?P<program_id>[^/]+)/exit-tickets/(?P<exit_ticket_id>[^/]+)/$',
        views.exit_ticket_answers, name='dashboard-exit-ticket-answers'),
    url('^volunteers/(?P<volunteer_id>[^/]+)/$',
        views.volunteer_details, name='dashboard-volunteer-details'),
    url('^students/(?P<student_id>[^/]+)/$',
        views.student_details, name='dashboard-student-details'),
    url('^training-sessions/$',
        views.training_sessions_index, name='dashboard-training-sessions-index'),
    url('^training-sessions/(?P<session_id>[^/]+)/$',
        views.training_session, name='dashboard-training-session'),
    url('^create-account/$', views.create_account, name='create-account')
]

hive/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.http import Http404

from hive.admin import admin_site
import programs.urls
import volunteers.urls
import dashboard.urls
import courses.urls


def not_found(request):
    raise Http404


if settings.SITE == 'programs':
    urlpatterns = [
        url(r'^', include('django.contrib.auth.urls')),
        url(r'^', include(programs.urls)),
    ]

elif settings.SITE == 'courses':
    urlpatterns = [
        url(r'^', include(courses.urls)),
        url(r'^', include('social_django.urls', namespace='social'))
    ]

else:
    urlpatterns = [
        url(r'^admin/', include(admin_site.urls)),
        url(r'^volunteer/', include(volunteers.urls)),
        url(r'^', include(dashboard.urls)),
        url(r'^', include('django.contrib.auth.urls')),
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

dashboard/models.py
from django.db import models

# Create your models here.

students/models.py
from datetime import date
from dateutil.relativedelta import relativedelta
from django.contrib.postgres.fields import JSONField
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from hive import google
from hive.utils import ordinal
from contacts.models import Person, DemographicsModel
from accounts.models import Account
from users.models import User
from programs.query import SemesterQuerySet
from . import constants
from . import utils
from . import scratch


class Student(Person, DemographicsModel, models.Model):
    user = models.OneToOneField(User, related_name='student', null=True, blank=True)
    account = models.ForeignKey(Account, related_name='students')
    date_added = models.DateTimeField(default=timezone.now)
    date_modified = models.DateTimeField(default=timezone.now)
    birth_date = models.DateField(_('Birth date'), null=True, blank=True)
    school_name = models.CharField(_('School name'), max_length=255, blank=True)
    grade_offset = models.IntegerField(
        default=0, help_text=('By default, grade is determined based on age. '
                              'Use offset if student is ahead or behind of '
                              'typical grade for their age.'))
    shirt_size = models.CharField(
        _('Shirt size'), max_length=5, choices=constants.SHIRT_SIZE_CHOICES, blank=True)

    extra_data = JSONField(null=True, blank=True)

    programs = models.ManyToManyField('programs.Program', through='programs.StudentRegistration')

    objects = SemesterQuerySet.as_manager(
        'registrations__program__start_date')

    def save(self, *args, **kwargs):
        self.date_modified = timezone.now()
        super().save(*args, **kwargs)

    def grade_as_of(self, as_of_date):
        # We get grade dynamically so we don't have to change it each year
        if not self.birth_date:
            return None

        # A good approximation of school grade is to take the age of the
        # student at the start of the school year (usually around 9/1) and
        # subtract 5.
        if as_of_date.month < 9:
            last_september = date(as_of_date.year - 1, 9, 1)
        else:
            last_september = date(as_of_date.year, 9, 1)

        last_september_age = relativedelta(
            last_september, self.birth_date).years

        return last_september_age - 5 + self.grade_offset

    @property
    def grade(self):
        return self.grade_as_of(date.today())

    @grade.setter
    def grade(self, value):
        # Grade can be set, but it will actually change grade_offset.
        self.grade_offset = 0
        assumed_grade = self.grade
        self.grade_offset = int(value) - assumed_grade

    @property
    def grade_name(self):
        if not self.grade:
            return None

        if self.grade == 0:
            return 'K'
        if self.grade <= 12:
            return ordinal(self.grade)
        else:
            return 'Graduate'

    @property
    def age(self):
        if not self.birth_date:
            return None
        return relativedelta(date.today(), self.birth_date).years

    def get_absolute_url(self):
        return reverse('dashboard-student-details', kwargs={'student_id': self.id})

    def __str__(self):
        return '{0.first_name} {0.last_name}'.format(self)


class StudentLogin(models.Model):
    """
    The logins stored here are not used for authentication. This is primarily used to store the
    login info that is printed student folder labels.
    """
    date_added = models.DateTimeField(auto_now_add=True)
    student = models.ForeignKey(Student, related_name='logins')
    service = models.CharField(
        choices=constants.STUDENT_LOGIN_SERVICE_CHOICES,
        max_length=255)
    username = models.CharField('Username/email', max_length=255)
    # FIXME This password should be strongly encrypted, only mentors and staff can decrypt
    password = models.CharField('Password', max_length=255)

    objects = SemesterQuerySet.as_manager(
        'student__registrations__program__sessions__date')

    class Meta:
        unique_together = ['service', 'username']

    def save(self, *args, **kwargs):

        if self.service == 'GOOGLE':
            google.create_or_update_student_account(self)
            # associate a Hive user account with the student's google account
            if not self.student.user_id:
                self.student.user = User.objects.create(email=self.username)
            else:
                self.student.user.email = self.username
                self.student.user.save()

        if self.service == 'SCRATCH':
            self.username = scratch.find_available_username(
                self.student.first_name,
                self.student.last_name
            )
            self.password = utils.generate_kidsafe_password()

        super().save(*args, **kwargs)

    def __str__(self):
        return '[{}] {}'.format(self.service, self.student)

dashboard/views.py
from collections import OrderedDict
from datetime import timedelta

from django.contrib import messages
from django.db.models import Min
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone

from programs.models import (
    Program, Session, VolunteerAttendance, StudentAttendance, Student, Volunteer)
from volunteers.models import TrainingSession
from volunteers.views import profile_required, get_profile
from courses.models import ExitTicket, StudentExitTicket


def create_account(request):
    url = reverse('volunteers-profile')
    next = request.GET.get('next')
    if next:
        url += '?next=' + next
    return HttpResponseRedirect(url)


def home(request):
    if not request.user or not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('volunteers-opportunities'))

    def view(request):
        volunteer = get_profile(request)

        # get upcoming programs, within a week "buffer" time
        time_ago = timezone.now() - timedelta(days=7)

        programs = Program.objects.with_semester() \
            .annotate(next_date=Min('sessions__date')) \
            .filter(sessions__date__gte=time_ago)

        # get upcoming training sessions
        training_sessions = volunteer.get_upcoming_training_sessions()
        show_all_sessions = volunteer.facilitated_training_sessions.all().count() > 0

        # get any pending requirements
        requirements = volunteer.requirements.filter(
            requirement_type__responsible_party='VOLUNTEER').pending()

        assignments = volunteer.assignments.filter(program__in=programs)

        context = {
            'show_all_programs': request.user.is_superuser and request.GET.get('show_all'),
            'requirements': requirements,
            'programs': programs.order_by('next_date'),
            'assignments': assignments,
            'training_sessions': training_sessions.distinct(),
            'show_all_sessions': show_all_sessions or request.user.is_superuser
        }
        return render(request, 'dashboard/home.html', context)

    return profile_required(view)(request)


@profile_required
def training_sessions_index(request):
    volunteer = get_profile(request)

    if request.user.is_superuser:
        past_sessions = TrainingSession.objects.filter(
            date__lt=timezone.now().date()
        )
    else:
        past_sessions = TrainingSession.objects.filter(
            date__lt=timezone.now().date(),
            facilitators=volunteer
        )

    context = {
        'upcoming_sessions': volunteer.get_upcoming_training_sessions(),
        'past_sessions': past_sessions.distinct()
    }

    return render(request, 'dashboard/training_sessions_index.html', context)


@profile_required
def training_session(request, session_id):
    volunteer = get_profile(request)
    session = get_object_or_404(TrainingSession, pk=session_id)

    if request.method == 'POST':
        session.attendees.clear()
        for volunteer_id in request.POST.getlist('volunteers'):
            session.attendees.add(int(volunteer_id))

    can_manage = request.user.is_superuser or volunteer in session.facilitators.all()
    context = {
        'session': session,
        'can_manage': can_manage
    }

    return render(request, 'dashboard/training_session.html', context)


@profile_required
def program_site(request, program_id, session_id=None):
    program = get_object_or_404(Program, pk=program_id)

    if session_id:
        session = Session.objects.get(pk=session_id)
    else:
        next_sessions = program.sessions.filter(date__gte=timezone.now().date()).order_by('date')
        if next_sessions.count() == 0:
            # if last session is over, just show the page for the last session
            session = program.sessions.order_by('-date')[0]
        else:
            session = next_sessions[0]

    # get existing attendances
    volunteer_attendances = OrderedDict()
    student_attendances = OrderedDict()

    for attendance in session.volunteer_attendances.all():
        volunteer_attendances[attendance.volunteer.pk] = attendance
    for attendance in session.student_attendances.all():
        student_attendances[attendance.student.pk] = attendance

    if session.type == 'PROGRAM':
        for student in program.students.order_by('first_name', 'last_name'):
            if not student_attendances.get(student.pk):
                student_attendances[student.pk] = StudentAttendance(
                    session=session, student=student)

    if request.method == 'POST':
        # Update existing attendances
        for id, attendance in volunteer_attendances.items():
            if request.POST.get('volunteer_{}_present'.format(id)):
                attendance.present = True
            else:
                attendance.present = False
            attendance.notes = request.POST.get('volunteer_{}_notes'.format(id))
            attendance.save()

        # Add any new attendances selected from dropdown
        for volunteer in program.volunteers.all():
            if volunteer.id in volunteer_attendances:
                continue
            if request.POST.get('volunteer_{}_present'.format(volunteer.id)):
                VolunteerAttendance(session=session, volunteer=volunteer, present=True).save()

        # Update student attendances
        for id, attendance in student_attendances.items():
            if request.POST.get('student_{}_present'.format(id)):
                attendance.present = True
            else:
                attendance.present = False
            attendance.notes = request.POST.get('student_{}_notes'.format(id))
            attendance.save()

        messages.add_message(request, messages.INFO, "Attendance saved.")
        return HttpResponseRedirect('.')

    sessions = [s.pk for s in program.sessions.all()]
    prev_session = None
    next_session = None
    i = sessions.index(session.pk)
    if i > 0:
        prev_session = sessions[i - 1]
    if i < len(sessions)-1:
        next_session = sessions[i + 1]

    # Get exit ticket results
    exit_ticket = None
    student_exit_tickets = []
    try:
        exit_ticket = ExitTicket.objects.get(course=program.course, session_number=session.number)
        for student in student_attendances:
            student_ticket = exit_ticket.get_student_best(student)
            if student_ticket:
                student_exit_tickets.append(student_ticket)
    except ExitTicket.DoesNotExist:
        pass

    other_volunteers = program.volunteers.exclude(pk__in=volunteer_attendances.keys())

    context = {
        'prev_session': prev_session,
        'next_session': next_session,
        'program': program,
        'session': session,
        'volunteer_attendances': volunteer_attendances,
        'student_attendances': student_attendances,
        'other_volunteers': other_volunteers,
        'exit_ticket': exit_ticket,
        'student_exit_tickets': student_exit_tickets
    }
    return render(request, 'dashboard/program_site.html', context)


@profile_required
def exit_ticket(request, program_id, student_exit_ticket_id):
    answers = StudentExitTicket.objects.get(pk=student_exit_ticket_id)
    context = {
        'answers': answers
    }
    return render(request, 'dashboard/exit_ticket_result.html', context)


@profile_required
def volunteer_details(request, volunteer_id):
    volunteer = get_object_or_404(Volunteer, pk=volunteer_id)
    context = {
        'volunteer': volunteer
    }
    return render(request, 'dashboard/volunteer_details.html', context)


@profile_required
def student_details(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    guardian = student.account.default_contact
    attendances = student.session_attendances.order_by('-session__date')
    context = {
        'student': student,
        'guardian': guardian,
        'attendances': attendances
    }
    return render(request, 'dashboard/student_details.html', context)


@profile_required
def exit_ticket_answers(request, exit_ticket_id, program_id=None):
    exit_ticket = get_object_or_404(ExitTicket, pk=exit_ticket_id)

    program = None
    if program_id:
        program = get_object_or_404(Program, pk=program_id)

    correct_answers = [q.correct_answers_set for q in exit_ticket.questions.all()]
    team = None
    if program:
        team = program.students.all()
    results = exit_ticket.build_results(correct_answers, team)

    def get_color(percent):
        # material red, orange, green 100
        if percent < 33:
            return '#ffcdd2'
        if percent > 66:
            return '#c8e6c9'
        return '#ffe0b2'

    for result in results:
        result['global_results']['color'] = get_color(result['global_results']['percent'])
        if result.get('team_results'):
            result['team_results']['color'] = get_color(result['team_results']['percent'])

    exit_tickets = [t.pk for t in exit_ticket.course.exit_tickets.all()]

    next_exit_ticket = None
    prev_exit_ticket = None
    prev_url = None
    next_url = None

    i = exit_tickets.index(exit_ticket.pk)
    if i > 0:
        prev_exit_ticket = exit_tickets[i - 1]
    if i < len(exit_tickets)-1:
        next_exit_ticket = exit_tickets[i + 1]

    if next_exit_ticket:
        kwargs = {'exit_ticket_id': next_exit_ticket}
        if program:
            kwargs['program_id'] = program.id
        next_url = reverse('dashboard-exit-ticket-answers', kwargs=kwargs)

    if prev_exit_ticket:
        kwargs = {'exit_ticket_id': prev_exit_ticket}
        if program:
            kwargs['program_id'] = program.id
        prev_url = reverse('dashboard-exit-ticket-answers', kwargs=kwargs)

    context = {
        'program_id': program and program.id or None,
        'prev_url': prev_url,
        'next_url': next_url,
        'exit_ticket': exit_ticket,

dashboard/templates/dashboard/base.html
{% extends "hive/base.html" %}

{% load static %}

{% block title %}<title>{{ page_title|default:"Hive" }}</title>{% endblock %}

{% block nav %}{% include "dashboard/includes/nav.html" %}{% endblock %}
{% block nav_mobile %}{% include "dashboard/includes/nav.html" %}{% endblock %}

{% block content %}
<div class="container">
  <div class="section" id="page_content">
    {% block page_content %}
    {% endblock %}
  </div>
</div>
{% endblock %}

dashboard/templates/dashboard/create_account.html
{% extends "programs/base.html" %}
{% load material_tags %}

{% block page_content %}
<h4>Create a new account</h4>
<p>
  Use the form below to create a new account with Bold Idea. You'll only need to do the first time you register
  with Bold Idea.
</p>
<form method="POST" action=".">
  <div class="row">
    <div class="col s12 m6">
      <div class="card">
        <div class="card-content">
          {% csrf_token %}
          <div class="input-field">
            <i class="material-icons prefix">account_circle</i>
            {{ form.email }}
            {% field_label form.email %}
          </div>
          <div class="input-field">
            <i class="material-icons prefix">lock</i>
            {{ form.password1 }}
            {% field_label form.password1 %}
          </div>
          <div class="input-field">
            <i class="material-icons prefix"></i>
            {{ form.password2 }}
            {% field_label form.password2 "Confirm password" %}
          </div>
        </div>
        <div class="card-action">
          <input type="submit" value="Submit" class="btn">
          {% if next %}
          <input type="hidden" name="next" value="{{ next }}">
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock %}

dashboard/templates/dashboard/exit_ticket_answers.html
{% extends "dashboard/base.html" %}
{% load static %}

{% block extracss %}
<link rel="stylesheet" type="text/css" href="{% static "courses/exit-ticket-results.css" %}">
<style>
  .session-nav {
    display: flex;
    align-items: center;
    justify-content: center;
  }
  .session-nav .exit-ticket-heading {
    flex: 1;
    text-align: center;
  }
</style>
{% endblock %}

{% block page_content %}
<h4>Exit Ticket Answers</h4>

<div class="row">
  <div class="col s12 session-nav">
    {% if prev_url %}
    <a class="prev btn btn-flat waves-effect" href="{{ prev_url }}"><i class="material-icons">navigate_before</i></a>
    {% endif %}
    <h5 class="exit-ticket-heading">{{ exit_ticket }}</h5>
    {% if next_url %}
    <a class="next btn btn-flat waves-effect" href="{{ next_url }}"><i class="material-icons">navigate_next</i></a>
    {% endif %}
  </div>
</div>

{% with preview_answers=True show_stats=True %}
{% include "courses/includes/exit_ticket_results.html" %}
{% endwith %}
{% endblock %}

dashboard/templates/dashboard/home.html
{% extends "dashboard/base.html" %}
{% load static markdown %}

{% block extracss %}
<style>
  .row.programs {
    display: flex;
    flex-wrap: wrap;
    align-content: flex-start;
  }
  .row.programs .col {
    margin-left: 0;
  }

  .requirements a {
    color: ;
  }
  .requirements .status-badge {
    font-size: .8em;
    border-radius: 1em;
    margin-left: 10px;
    padding: 4px 8px;
    color: white;
    background-color: #757575;
  }
  .requirement-incomplete .status-badge {
    background-color: #d84315;
  }
  .requirement-processing .status-badge {
    background-color: #2196F3;
  }
</style>
{% endblock %}

{% block page_content %}
	<div class="section">
    {% if requirements|length > 0 %}
    <h4>Pending Requirements</h4>
    <p>
      The following requirements are still pending. All requirements must be completed before your first
      session. Click a requirement below for more information.
    </p>
    <div class="collection requirements">
      {% for requirement in requirements %}
      <a href="#requirement-{{ requirement.id }}" class="collection-item modal-trigger requirement-{{ requirement.status|lower }}">
        {{ requirement.name }} <span class="status-badge">{{ requirement.get_status_display }}</span>
      </a>
      {% endfor %}
    </div>
    {% for requirement in requirements %}
    <div class="modal" id="requirement-{{ requirement.id }}">
      <div class="modal-content">
        <h4>{{ requirement.name }}</h4>
        {{ requirement.instructions|markdown }}
      </div>
      <div class="modal-footer">
        <a href="#!" class="modal-action modal-close btn flat">Close</a>
      </div>
    </div>
    {% endfor %}
    {% endif %}
    {% if training_sessions|length > 0 %}
    <h4>Upcoming Semester Kickoff Sessions</h4>
    <p>Mentors are required to attend at least one kickoff session per semester.</p>
    <div class="collection">
      {% for session in training_sessions %}
      <a class="collection-item" href="{% url "dashboard-training-session" session_id=session.id %}">
        {{ session.name }} - {{ session.date|date:"N j" }}, {{ session.start_time|date:"P" }}
      </a>
      {% endfor %}
    </div>
    {% endif %}

    {% if show_all_programs %}
      <h4>All Program Sites</h4>
      <div class="row programs">
        {% for program in programs %}
        <div class="col s12 m6 xl4">
          {% include "dashboard/includes/program_site_card.html" %}
        </div>
        {% endfor %}
      </div>
    {% elif assignments|length > 0 %}
      <h4>My Programs</h4>
      {% regroup assignments by role as assignments_by_role %}
      {% for role in assignments_by_role %}
      <h5>{{ role.grouper|title }}</h5>
      <div class="row programs">
        {% for assignment in role.list %}
        <div class="col s12 m6 xl4">
          {% with assignment.program as program %}
          {% include "dashboard/includes/program_site_card.html" %}
          {% endwith %}
        </div>
        {% endfor %}
      </div>
      {% endfor %}
    {% endif %}

    {% if show_all_sessions %}
    <div class="row">
      <a href="{% url "dashboard-training-sessions-index" %}" class="btn">View past kickoff sessions</a>
    </div>
    {% endif %}
    <div class="row">
      <h4>Volunteer Opportunities</h4>
      <p>
        Click below to see our volunteer opportunities!
      </p>
      <p>
        <a class="btn" href="{% url "volunteers-opportunities" %}">Sign Up</a>
      </p>
    </div>
  </div>
{% endblock %}

{% block extrajs %}
<script type="text/javascript">
  (function($) {
    $(document).ready(function() {
      $('.modal').modal();
      $('tr[data-url]').on('click', function(event) {
        window.location.href = $(this).data('url');
      });
    });
  })(jQuery);
</script>
{% endblock %}

dashboard/templates/dashboard/student_details.html
{% extends "dashboard/base.html" %}
{% block extracss %}
{{ block.super }}
<style>
  .clip:hover {
    background-color: #ccc;
    border-radius: 4px;
  }
  .modal.student-login h5 {
    margin-bottom: 1em;
  }
  .attendance.absent {
    color: #e53935;
  }
  tr.future, tr.future .attendance {
    background: #eee;
    color: #aaa;
  }
</style>
{% endblock %}
{% block page_content %}

<h4>{{ student }}</h4>
<div class="row">
  <div class="col s12">
    <p>
      <strong>Age:</strong> {{ student.age }}<br>
      <strong>Grade:</strong> {{ student.grade }}<br>
      {% if student.school %}
      <strong>School:</strong> {{ student.school }}
      {% endif %}
    </p>
  </div>
</div>


<h4>Contacts</h4>
<div class="row">
  <div class="col s12 m6">
    <div class="card-panel">
      <h5>
        {{ guardian }} ({{ guardian.relationship }})
      </h5>
      <p>
        {{ guardian.phone }}<br>
        {{ guardian.email }}
      </p>
    </div>
  </div>
</div>

{% if student.logins.count > 0 %}
<h4>Logins</h4>
<div class="row">
  <div class="col s12">
    <p>Click a login below to view the credentials.</p>
    <div class="collection">
      {% for login in student.logins.all %}
      <a href="#studentLogin{{ login.id }}" class="collection-item modal-trigger">{{ login.get_service_display }}</a>
      <div id="studentLogin{{ login.id }}" class="modal student-login">
        <div class="modal-content">
          <h5>{{ login.get_service_display }} Login for {{ login.student }}</h5>
          <div class="row credentials">
            <div class="col s12">
              <label for="id_username"><i class="material-icons left">account_circle</i>Username:</label>
              <input id="id_username" type="text" class="clip" readonly value="{{ login.username }}">
            </div>
            <div class="col s12">
              <label for="id_password"><i class="material-icons left">lock</i>Password:</label>
              <input id="id_password" type="text" class="clip" readonly value="{{ login.password }}">
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <a href="#!" class="modal-action modal-close waves-effect btn-flat">Close</a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endif %}

<h4>Attendance</h4>
<div class="row">
  <div class="col s12">
    {% regroup attendances by session.program as attended_programs %}
    {% for program_attendance in attended_programs %}
    <div class="card-panel">
      <h5>{{ program_attendance.grouper.name }}</h5>
      <table>
        <thead><tr><th>Session</th><th>Date</th><th>Status</th><th>Notes</th></tr></thead>
        <tbody>
          {% for attendance in program_attendance.list %}
          <tr{% if attendance.is_future %} class="future"{% endif %}>
            <td>{{ attendance.session.description }}</td>
            <td>{{ attendance.session.date }}</td>
            <td>
              <span class="attendance {{ attendance.status|lower }}">{{ attendance.get_status_display }}</span>
            </td>
            <td>{{ attendance.notes }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

{% block extrajs %}
{{ block.super }}
<script>
  (function($) {
    $(document).ready(function() {
      $('.modal').modal();
      $('.clip').on('focus', function(e) {
        $(this).select();
        try {
          document.execCommand('copy');
          Materialize.toast('Copied to clipboard.', 1000);
        } catch (e) {
          Materialize.toast('Sorry, your browser does not support clipboard.', 3000);
        }
        try {
          window.getSelection().removeAllRanges();
        } catch (e) {
          try {
            document.selection.empty();
          } catch(e) {}
        }
      });
    });
  })(jQuery);
</script>
{% endblock %}

dashboard/templates/dashboard/training_session.html
{% extends "dashboard/base.html" %}
{% load markdown thumbnail static %}

{% block extracss %}
<style>
  .attendance-name label {
    width: 0;
  }
  .attendance-name {
    white-space: nowrap;
  }
</style>
{% endblock %}

{% block page_content %}
<h3>{{ session.name }}</h3>

<div class="card-panel">
  {% if session.description %}{{ session.description|markdown }}{% endif %}
  <p>
    <strong>Date:</strong> {{ session.date_description }}
  </p>
  {% with session.location as location %}
  <p>
    <strong>Location:</strong> {{ location.name }}<br>
    <a target="_blank" href="https://maps.google.com/maps/place/{{ location.address1 }},+{{ location.city }},+{{ location.state }}+{{ location.postal_code }}">
      {{ location.address1 }} {{ location.address2 }}<br>
      {{ location.city }}, {{ location.state }} {{ location.postal_code }}
    </a>
  </p>
  {% endwith %}
</div>

{% if session.location_info or session.location.instructions %}
<div class="card">
  <div class="card-content">
    <h4 class="card-title">Location Info</h4>
    {{ session.location_info|default:session.location.instructions|markdown }}
  </div>
</div>
{% endif %}

{% if can_manage %}
<form method="post" action=".">{% csrf_token %}
  <div class="row">
    <div class="card-panel col s12">
      <ul class="component collection with-header">
        <li class="collection-header"><h5>Attendance</h5></li>
        {% for volunteer in session.invitees.all %}
        <li class="collection-item">
          <div class="row">
            <div class="attendance-name col s12 m5">
              <div class="input-field">
                <input type="checkbox" name="volunteers" value="{{ volunteer.id }}"
                  id="id_volunteer_{{ volunteer.id }}"{% if volunteer in session.attendees.all %} checked{% endif %}>
                <label for="id_volunteer_{{ volunteer.id }}"></label>
                <a class="chip" href="{% url "dashboard-volunteer-details" volunteer_id=volunteer.id %}">
                  {% if volunteer.photo %}
                  <img src="{% thumbnail volunteer.photo 32x32 crop %}">
                  {% else %}
                  <img src="{% static "hive/images/generic-user.png" %}" height="32" width="32">
                  {% endif %}
                  {{ volunteer }}
                </a>
              </div>
            </div>
          </div>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
  <div class="right-align">
    <input class="btn" type="submit" value="Save">
  </div>
</form>
{% endif %}
{% endblock %}

dashboard/templates/dashboard/volunteer_details.html
{% extends "dashboard/base.html" %}
{% load thumbnail static %}
{% block extracss %}
<style>
  .photo {
    text-align: center;
  }
</style>
{% endblock %}
{% block page_content %}

<div class="card-panel">
  <div class="row">
    <div class="photo col s12 m5 l4">
      <img class="circle" src="{% thumbnail volunteer.photo 192x192 crop upscale %}">
    </div>
    <div class="col s12 m7 l8">
      <h4>{{ volunteer.name }}</h4>
      <p>
        {{ volunteer.email }}
      </p>
      <p>
        {{ volunteer.phone }}
      </p>
    </div>
  </div>
</div>

{% endblock %}